In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor_one_d= tf.constant([2,0,-3,9,90],dtype=tf.float64)
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  9. 90.], shape=(5,), dtype=float64)


In [3]:
# for memory use lower precision tensor



In [4]:
#tensor_one_d= tf.constant([2,0.2,-3,9,90],dtype=tf.int64)
#print(tensor_one_d)

# This will give an error
# TypeError: Cannot convert [2, 0.2, -3, 9, 90] to EagerTensor of dtype int64


In [5]:
# To solve this issue cast method can be used
tensor_one_d= tf.constant([2,0.2,-3,9,90],dtype=tf.float64)
print(tensor_one_d)

print(" ")

casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.int16)
print(casted_tensor_one_d)


tf.Tensor([ 2.   0.2 -3.   9.  90. ], shape=(5,), dtype=float64)
 
tf.Tensor([ 2  0 -3  9 90], shape=(5,), dtype=int16)


In [6]:
# caste into boolian

tensor_one_d= tf.constant([2,0.,-3,9,90],dtype=tf.float32)
print(tensor_one_d)

print(" ")

casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool)
print(casted_tensor_one_d)


tf.Tensor([ 2.  0. -3.  9. 90.], shape=(5,), dtype=float32)
 
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [7]:
tensor_bool = tf.constant([True,True,False])

print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [8]:
tensor_string = tf.constant(["TensorFlow and PYTorch"])
print(tensor_string)

tf.Tensor([b'TensorFlow and PYTorch'], shape=(1,), dtype=string)


In [9]:
# convert numpy array to tensor



In [10]:
np_arr =  np.array([1,2,3])
print(np_arr)

[1 2 3]


In [11]:
convert_tensor = tf.convert_to_tensor(np_arr)
print(convert_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [12]:
# tf.eye

# construct an identity matrix or a batch of matrices.

eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=None,
    batch_shape=None,
    dtype= tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [13]:
print(eye_tensor*8)

tf.Tensor(
[[8. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0.]
 [0. 0. 8. 0. 0.]
 [0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 8.]], shape=(5, 5), dtype=float32)


In [14]:
# num_columns = None means num_rows = num_columns

eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=3,
    batch_shape=None,
    dtype= tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [15]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=5,
    batch_shape=None,
    dtype= tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]], shape=(5, 5), dtype=bool)


In [16]:
# change batch_shape

eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=5,
    batch_shape=[2,], # 2  5*5 identity matrices
    dtype= tf.dtypes.int64,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]

 [[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]], shape=(2, 5, 5), dtype=int64)


In [17]:
# tf. fill

# creates a tensor filled with a scaler value


In [18]:

tensor_fill = tf.fill(
    dims = [1,2],
    value=5,
    name=None
)
print(tensor_fill)

tf.Tensor([[5 5]], shape=(1, 2), dtype=int32)


In [19]:

tensor_fill = tf.fill(
    dims = [3,3], # 2D matrix
    value=5,
    name=None
)
print(tensor_fill)

tf.Tensor(
[[5 5 5]
 [5 5 5]
 [5 5 5]], shape=(3, 3), dtype=int32)


In [20]:

tensor_fill = tf.fill(
    dims = [3,3,3], # 3D matrix
    value=5,
    name=None
)
print(tensor_fill)

tf.Tensor(
[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]], shape=(3, 3, 3), dtype=int32)


In [21]:
# tf. ones

# Creates a tensor with all elements set to 1.



In [22]:
tensor_ones= tf.ones(
    shape=[1,3],
    dtype = tf.dtypes.float32,
    name=None
)
print(tensor_ones)

tf.Tensor([[1. 1. 1.]], shape=(1, 3), dtype=float32)


In [23]:
tensor_ones= tf.ones(
    shape=[3,3],
    dtype = tf.dtypes.int32,
    name=None
)
print(tensor_ones)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


In [24]:
tensor_ones= tf.ones(
    shape=[5,3],
    dtype = tf.dtypes.int32,
    name=None
)
print(tensor_ones)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]], shape=(5, 3), dtype=int32)


In [25]:
tensor_ones= tf.ones(
    shape=[5,3,2],
    dtype = tf.dtypes.int32,
    name=None
)
print(tensor_ones)

tf.Tensor(
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]], shape=(5, 3, 2), dtype=int32)


In [26]:
# tf.ones_like

# creates a tensor of all ones that has the same shape as input


In [27]:
tensor_one_like= tf.ones_like(
    input = tensor_fill ,
    dtype=None,
    name=None
)
print(tensor_one_like)

tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(3, 3, 3), dtype=int32)


In [28]:
# tf. zeros

# creates a tensor with all elements set to 0


In [29]:
tensor_zero = tf.zeros(
    shape = [3,2],
    dtype = tf.dtypes.int32,
    name=None
)
print(tensor_zero)


tf.Tensor(
[[0 0]
 [0 0]
 [0 0]], shape=(3, 2), dtype=int32)


In [30]:
tensor_zero = tf.zeros(
    shape = [3,2,3],
    dtype = tf.dtypes.int32,
    name=None
)
print(tensor_zero)

tf.Tensor(
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]], shape=(3, 2, 3), dtype=int32)


In [31]:
# tf.shape

# Returns a tensor containing the shape of the input tensor


In [32]:
tensor_three_d=tf.constant([
 [[1,2,0],
 [3,5,-1]],

[[4,5,6],
 [7,-8,9]],

[[10,11,12],
 [13,-14,15]],

 [[16,17,18],
 [13,-14,15]]
])
print(tensor_three_d)



tf.Tensor(
[[[  1   2   0]
  [  3   5  -1]]

 [[  4   5   6]
  [  7  -8   9]]

 [[ 10  11  12]
  [ 13 -14  15]]

 [[ 16  17  18]
  [ 13 -14  15]]], shape=(4, 2, 3), dtype=int32)


In [33]:
print(tf.shape(tensor_three_d))


tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [34]:
# tf. rank

# Return the rank of a tensor


In [35]:
# shape of tensor 't' is [2,2,3]

t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

tf.rank(t)


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [36]:

t = tf.constant([[1,1,1],[2,2,2]])

tf.rank(t)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [37]:
# tf. size

# Returns the size of  a tensor


In [38]:
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])


tensor_size= tf.size(
    input=t,
    out_type=tf.dtypes.int32,
    name=None
)

print(tensor_size) # 12 elements

tf.Tensor(12, shape=(), dtype=int32)


In [39]:
t = tf.constant([[1,1,1],[2,2,2]])


tensor_size= tf.size(
    input=t,
    out_type=tf.dtypes.int32,
    name=None
)

print(tensor_size) # 6 elements

tf.Tensor(6, shape=(), dtype=int32)


In [40]:
# tf.random.normal

# Outputs random values from a normal distribution



In [41]:
tensor_normal = tf.random.normal(
    shape =[3,4],
    mean = 0.0,
    stddev=1.0,
    dtype = tf.dtypes.float32,
    seed=None,
    name=None
)

print(tensor_normal)

tf.Tensor(
[[-0.69508284  0.29647443 -1.8256868  -0.5174599 ]
 [-0.82659656  0.6598522   1.1472871   0.7347902 ]
 [ 1.9119201   0.34458348 -1.1466113   0.09250392]], shape=(3, 4), dtype=float32)


In [42]:
# change the mean

tensor_normal = tf.random.normal(
    shape =[3,4],
    mean = 100.0,
    stddev=1.0,
    dtype = tf.dtypes.float32,
    seed=None,
    name=None
)

print(tensor_normal)

tf.Tensor(
[[100.83498  100.60084   99.615204 100.14299 ]
 [101.519325 100.77097   99.24902   98.68998 ]
 [102.00322  100.02967  101.23886  100.61433 ]], shape=(3, 4), dtype=float32)


In [44]:
# change the mean and standard deviation


tensor_normal = tf.random.normal(
    shape =[3,4],
    mean = 100.0,
    stddev=5.0,
    dtype = tf.dtypes.float32,
    seed=None,
    name=None
)

print(tensor_normal)

tf.Tensor(
[[ 92.134445  95.13879   97.6855   101.3835  ]
 [ 95.70464   96.77932   92.23961   98.58325 ]
 [109.467575  98.04249   92.71533  104.73253 ]], shape=(3, 4), dtype=float32)


In [45]:


tensor_normal = tf.random.normal(
    shape =[3,4],
    mean = -100.0,
    stddev=-5.0,
    dtype = tf.dtypes.float32,
    seed=None,
    name=None
)

print(tensor_normal)

tf.Tensor(
[[-107.744606 -102.70503   -93.524704  -93.60624 ]
 [-107.94829   -97.87954   -98.99679   -92.19858 ]
 [ -90.59363   -98.92517  -106.8613   -103.81096 ]], shape=(3, 4), dtype=float32)


In [ ]:
# tf. random. uniform

# Outputs random values from a uniform distribution



In [48]:
tensor_uniform = tf.random.uniform(
    shape=[4,3],
    minval=0,
    maxval=None,
    dtype = tf.dtypes.float32,
    seed=None,
    name=None

)
print(tensor_uniform)

tf.Tensor(
[[0.99079716 0.9738599  0.2213571 ]
 [0.08549404 0.29843342 0.11610544]
 [0.36522496 0.47726297 0.8124505 ]
 [0.94018126 0.9500427  0.6179464 ]], shape=(4, 3), dtype=float32)


In [49]:
#change max and min value
# max = 1 default value and min=0 default value

tensor_uniform = tf.random.uniform(
    shape=[4,3],
    minval=-1,
    maxval=10,
    dtype = tf.dtypes.float32,
    seed=None,
    name=None

)
print(tensor_uniform)

tf.Tensor(
[[ 6.5566425   1.2838387   3.8128595 ]
 [ 8.808012    9.775817    7.4145308 ]
 [ 2.0338955   6.4800587  -0.39369845]
 [ 0.9045812   3.430077    5.54754   ]], shape=(4, 3), dtype=float32)


In [59]:
# set a value of seed to get same out put each time when we run code

tf.random.set_seed(10)
tensor_uniform = tf.random.uniform(
    shape=[4,3],
    minval=-1,
    maxval=10,
    dtype = tf.dtypes.float32,
    seed=10,
    name=None

)
print(tensor_uniform)

tf.Tensor(
[[9.5322    8.4432125 5.812717 ]
 [1.4109325 2.473528  6.701801 ]
 [0.4933083 8.925728  5.362786 ]
 [7.9165754 1.4701917 5.7715526]], shape=(4, 3), dtype=float32)
