In [ ]:
import tensorflow as tf

In [ ]:
# tf. linalg. matmul

# Mutliplication matrix a by matrix b producing a*b


In [ ]:
# when we multiply matrix
# No. of columns of 1st matrix should always match the number
# of rows of the second matrix.

a = tf.constant([
    [3,1,9,6,5],
    [0,1,7,3,2],
    [1,5,1,2,0],
    [7,3,0,9,0]
])


b = tf.constant([
    [3,1,9,6,5],
    [0,1,7,3,2],
    [1,5,1,2,0],
    [7,3,0,9,0],
    [1,4,5,9,10]
])

tensor_matrix = tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)
print(tensor_matrix)


tf.Tensor(
[[ 65  87  68 138  67]
 [ 30  53  24  62  22]
 [ 18  17  45  41  15]
 [ 84  37  84 132  41]], shape=(4, 5), dtype=int32)


In [ ]:

a = tf.constant([
   [1,2,3],
   [4,5,6]
])


b = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

tensor_matrix = tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)
print(tensor_matrix)


tf.Tensor(
[[30 36 42]
 [66 81 96]], shape=(2, 3), dtype=int32)


In [ ]:
a = tf.constant([
   [1,2,3],
   [4,5,6]
])

print(a)

print("")

print(a.shape,tf.transpose(a))


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

(2, 3) tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [ ]:
 # a * transpose(b)


a = tf.constant([
   [1,2,3],
   [2,1,1]
])


b = tf.constant([
    [1,2,3],
    [4,5,6],
    [2,2,2]
])

print(a)
print(" ")

print(b.shape,tf.transpose(b))

print(" ")

tensor_matrix = tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=True,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)
print(tensor_matrix)


tf.Tensor(
[[1 2 3]
 [2 1 1]], shape=(2, 3), dtype=int32)
 
(3, 3) tf.Tensor(
[[1 4 2]
 [2 5 2]
 [3 6 2]], shape=(3, 3), dtype=int32)
 
tf.Tensor(
[[14 32 12]
 [ 7 19  8]], shape=(2, 3), dtype=int32)


In [ ]:
a_three_d = tf.constant(
    [
      [[1,2],
      [3,5]],

      [[10,2],
       [1,0]],

      [[5,8],
       [2,7]],

      [[2,1],
       [4,3]]
        ]
)
print(a_three_d)

b_three_d = tf.constant(
    [
      [[1,2,0],
      [3,5,-1]],

      [[10,2,0],
       [1,0,2]],

      [[5,8,8],
       [2,7,0]],

      [[2,1,9],
       [4,3,-2]]
        ]
)
print(b_three_d)


tf.Tensor(
[[[ 1  2]
  [ 3  5]]

 [[10  2]
  [ 1  0]]

 [[ 5  8]
  [ 2  7]]

 [[ 2  1]
  [ 4  3]]], shape=(4, 2, 2), dtype=int32)
tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  8]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4  3 -2]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(a_three_d.shape,b_three_d.shape)


(4, 2, 2) (4, 2, 3)


In [ ]:
print(tf.linalg.matmul(a_three_d,b_three_d))


tf.Tensor(
[[[  7  12  -2]
  [ 18  31  -5]]

 [[102  20   4]
  [ 10   2   0]]

 [[ 41  96  40]
  [ 24  65  16]]

 [[  8   5  16]
  [ 20  13  30]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(a_three_d[0],b_three_d[0])


tf.Tensor(
[[1 2]
 [3 5]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [ ]:
a_three_d[0]@b_three_d[0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 12, -2],
       [18, 31, -5]], dtype=int32)>

In [ ]:
a_three_d[2]@b_three_d[2]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[41, 96, 40],
       [24, 65, 16]], dtype=int32)>

In [ ]:
# tf. linalg.band_part

# Copy a tensor setting everything outside a central band in each
# innermost matrix to zero


In [ ]:
x =  tf.constant([[0,1,2,3],
                  [-1,0,1,2],
                  [-2,-1,0,1],
                  [-3,-2,-1,0]])
x

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [-1,  0,  1,  2],
       [-2, -1,  0,  1],
       [-3, -2, -1,  0]], dtype=int32)>

In [ ]:
a =  tf.constant([
    [1,5,1],
    [7,9,3],
    [1,3,1]
    ])
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 5, 1],
       [7, 9, 3],
       [1, 3, 1]], dtype=int32)>

In [ ]:
"""
Condition:- m for row and n for column

m = 0, n = 0, m-n =0, n-m =0

False             True                 False          True
        True                                    True
                                True
(num_lower<0 || (m-n)<=num_lower) && (num_upper<0 || (n-m)<=num_upper)

"""

'\nCondition:- m for row and n for column\n\nm = 0, n = 0, m-n =0, n-m =0\n\nFalse             True                 False          True\n        True                                    True\n                                True\n(num_lower<0 || (m-n)<=num_lower) && (num_upper<0 || (n-m)<=num_upper)\n\n'

In [ ]:

tensor_band_part=tf.linalg.band_part(a,0,0)
print(tensor_band_part)

tf.Tensor(
[[1 0 0]
 [0 9 0]
 [0 0 1]], shape=(3, 3), dtype=int32)


In [ ]:
# tf. linalg. det

# Computes the determinant of one or more square matrices

# No of rows should be equal to No. of columns


In [ ]:
x =  tf.constant([[1.0,2.0],
                  [5.0,6.0]])

y =  tf.constant([[1.0,2.0],
                  [3.0,4.0]])

In [ ]:
tensor_deter= tf.linalg.det(x,y)
tensor_deter

<tf.Tensor: shape=(), dtype=float32, numpy=-4.0>

In [ ]:
# Inverse of a matrix

# A inverse* A = Identity matrix

# tf.linalg.inv

# Cmputes the inverse of one or more square matrices or their
# adjoints( conjuagate transposes)


In [ ]:
x =  tf.constant([[1.0,2.0],
                  [5.0,6.0]])

y =  tf.constant([[1.0,2.0],
                  [3.0,4.0]])

In [ ]:
tf.linalg.inv(x,adjoint=True)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.5 ,  1.25],
       [ 0.5 , -0.25]], dtype=float32)>

In [ ]:
# tf. einsum

# Tensor contraction over specified indices and outer product


In [ ]:
a = tf.constant([[1,2,],
               [3,4]])

b = tf.constant([[1,2,],
               [3,4]])


In [ ]:
tf.linalg.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
tf.einsum("ij,jk->ik",a,b)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
a =  tf.constant([2,6,5,2])
b = tf.constant([0,1,3,2])



In [ ]:
tf.einsum("i,j->",a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=90>

In [ ]:
tf.einsum("i,j->ji",a,b)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  0,  0,  0],
       [ 2,  6,  5,  2],
       [ 6, 18, 15,  6],
       [ 4, 12, 10,  4]], dtype=int32)>

In [45]:
tf.einsum("i,i->",a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [46]:
tf.einsum("j,j->",a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=25>