In [1]:
import tensorflow as tf

In [ ]:
# tf. expand_dims

# Returns a tensor with a length 1 axis inserted at index axis


In [4]:
a = tf.constant([1,2,3,4,5])
a.shape


TensorShape([5])

In [5]:
tf.expand_dims(a,axis=0)

# add extra dimension of size 1


<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 2, 3, 4, 5]], dtype=int32)>

In [6]:
tf.expand_dims(a,axis=1)

# 2D tensor


<tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5]], dtype=int32)>

In [9]:
a = tf.constant([[1,2,],
                 [3,4]])

a.shape

TensorShape([2, 2])

In [10]:
tf.expand_dims(a,axis=0)

#convert 2D to 3D

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [11]:
tf.expand_dims(a,axis=1)


<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

In [12]:
tf.expand_dims(a,axis=-1)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# tf. squeeze

# Removes dimensions of size 1 from the shape of a tensor



In [15]:
a = tf.expand_dims(a,axis=-1)
a.shape
print(a)

tf.Tensor(
[[[[1]]

  [[2]]]


 [[[3]]

  [[4]]]], shape=(2, 2, 1, 1), dtype=int32)


In [14]:
tf.squeeze(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# tf.reshape

# Reshapes a tensor



In [17]:
a = tf.constant([1,2,3,4,5,6,7,8,9])
print(a)
print(" ")
print(a.shape)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
 
(9,)


In [19]:
tf.reshape(a,[1,9])


<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)>

In [22]:
tf.reshape(a,[3,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [25]:
tf.reshape(a,[1,-1])


<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)>

In [26]:
tf.reshape(a,[3,3,1])



<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]], dtype=int32)>

In [30]:
tf.reshape(a,[3,-1])
# -1 means tensorflow will figure out what is the right value for that
# dimension


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [34]:
a1 = tf.constant([[1,2,3],
                 [4,5,6]])

print(a1)
print("")

print("shape of a1 :",a1.shape)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

shape of a1 : (2, 3)


In [37]:
tf.reshape(a1,[-1])


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
# tf. concat

# Concatenates tensors along one dimension



In [44]:
tensor_1 = tf.constant([[1,2,3],[4,5,6]])
print(tensor_1)

print(" ")


tensor_2 = tf.constant([[10,11,12],[7,8,9]])
print(tensor_2)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
 
tf.Tensor(
[[10 11 12]
 [ 7  8  9]], shape=(2, 3), dtype=int32)


In [45]:
tf.concat([tensor_1,tensor_2],axis=0)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [ 7,  8,  9]], dtype=int32)>

In [46]:
tf.concat([tensor_1,tensor_2],axis=1)


<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9]], dtype=int32)>

In [50]:
t1= tf.constant([
    [[1,2],
     [3,4]],

    [[5,6],
     [7,8]]
])

t2= tf.constant([
    [[10,20],
     [30,40]],

    [[50,60],
     [70,80]]
])

In [51]:
print(t1.shape)
print("")
print(t2.shape)


(2, 2, 2)

(2, 2, 2)


In [52]:
tf.concat([t1,t2],axis=0)


<tf.Tensor: shape=(4, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]], dtype=int32)>

In [53]:
tf.concat([t1,t2],axis=1)


<tf.Tensor: shape=(2, 4, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [10, 20],
        [30, 40]],

       [[ 5,  6],
        [ 7,  8],
        [50, 60],
        [70, 80]]], dtype=int32)>

In [54]:
tf.concat([t1,t2],axis=-1)


<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  2, 10, 20],
        [ 3,  4, 30, 40]],

       [[ 5,  6, 50, 60],
        [ 7,  8, 70, 80]]], dtype=int32)>

In [55]:
tf.concat([t1,t2],axis=-2)


<tf.Tensor: shape=(2, 4, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [10, 20],
        [30, 40]],

       [[ 5,  6],
        [ 7,  8],
        [50, 60],
        [70, 80]]], dtype=int32)>

In [ ]:
# tf.stack

# Stacks a list of rank-R tensors into one rank - (R+1) tensor

# with contact there is no extra dimension is created
# with stackk if input is 2D then output will be 3D


In [57]:
tf.stack([t1,t2],axis=0)



<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[10, 20],
         [30, 40]],

        [[50, 60],
         [70, 80]]]], dtype=int32)>

In [58]:
tensor_1 = tf.constant([[1,2,3],[4,5,6]])
print(tensor_1)

print(" ")


tensor_2 = tf.constant([[10,11,12],[7,8,9]])
print(tensor_2)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
 
tf.Tensor(
[[10 11 12]
 [ 7  8  9]], shape=(2, 3), dtype=int32)


In [59]:
tf.stack([tensor_1,tensor_2],axis=0)


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [ 7,  8,  9]]], dtype=int32)>

In [60]:
tf.stack([tensor_1,tensor_2],axis=1)


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [10, 11, 12]],

       [[ 4,  5,  6],
        [ 7,  8,  9]]], dtype=int32)>

In [61]:
tf.stack([tensor_1,tensor_2],axis=-1)


<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1, 10],
        [ 2, 11],
        [ 3, 12]],

       [[ 4,  7],
        [ 5,  8],
        [ 6,  9]]], dtype=int32)>

In [ ]:
# tf. pad

# Pads a tensor



In [63]:
tensor_1 = tf.constant([[1,2,3],[4,5,6]])
print(tensor_1)

print(" ")


tensor_2 = tf.constant([[10,11,12],[7,8,9]])
print(tensor_2)

print(" ")

paddings = tf.constant([[1,1],[2,2]])
print(paddings)

# contant values is 0



tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
 
tf.Tensor(
[[10 11 12]
 [ 7  8  9]], shape=(2, 3), dtype=int32)
 
tf.Tensor(
[[1 1]
 [2 2]], shape=(2, 2), dtype=int32)


In [69]:
tf.pad(tensor_1,paddings,"CONSTANT")



<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
# paddings values permit us to know how many values
# for at the top we are gonna add
# how many values at the bottom we are gonna add
# how many values to the left and right we are gonna add


In [70]:
tf.pad(tensor_1,paddings,"REFLECT")


<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[6, 5, 4, 5, 6, 5, 4],
       [3, 2, 1, 2, 3, 2, 1],
       [6, 5, 4, 5, 6, 5, 4],
       [3, 2, 1, 2, 3, 2, 1]], dtype=int32)>

In [ ]:
# Reflect means value around tensors will be from tensor itself



In [ ]:
# tf.gather

# Gather slices from params axis according to indices

In [78]:
a = tf.constant([1,2,3,4,5])
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [79]:
# when we slice tensor like...
# values will come in order if we do not want it like this
# we can use gather method

a[1:3]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [82]:
tf.gather(a,[0,2,4],axis=0)



<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 5], dtype=int32)>

In [84]:
a = tf.constant([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15],
                 [16,17,18,19,20]])

a

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)>

In [89]:
tf.gather(a,[1,2],axis=0)


<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]], dtype=int32)>

In [92]:
tf.gather(a,[3,4],axis=1)



<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]], dtype=int32)>

In [94]:
tf.gather(a,[[1,2],[3,4]],axis=1)



<tf.Tensor: shape=(4, 2, 2), dtype=int32, numpy=
array([[[ 2,  3],
        [ 4,  5]],

       [[ 7,  8],
        [ 9, 10]],

       [[12, 13],
        [14, 15]],

       [[17, 18],
        [19, 20]]], dtype=int32)>

In [99]:
a = tf.constant([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15],
                 [16,17,18,19,20]])

a

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)>

In [101]:
tf.gather_nd(a,[[1,2],[3,4]])

# pick up elements directly from tensor


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 8, 20], dtype=int32)>