# Tensor :- Tensors are Multi Dimensional Arrays

An Array is an ordered arrangement of numbers


In [1]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

#tensor with value 4 with no shape

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

#tensor with 3 values . 1D tensor all integer values

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [8]:
tensor_one_d_float = tf.constant([2,0,-3,0.8])
print(tensor_one_d_float)

# 1D tensor with type float

tf.Tensor([ 2.   0.  -3.   0.8], shape=(4,), dtype=float32)


In [11]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6]
    ])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [16]:
tensor_three_d=tf.constant([
 [[1,2,0],
 [3,5,-1]],

[[4,5,6],
 [7,-8,9]],

[[10,11,12],
 [13,-14,15]],

 [[16,17,18],
 [13,-14,15]]
])
print(tensor_three_d)

tf.Tensor(
[[[  1   2   0]
  [  3   5  -1]]

 [[  4   5   6]
  [  7  -8   9]]

 [[ 10  11  12]
  [ 13 -14  15]]

 [[ 16  17  18]
  [ 13 -14  15]]], shape=(4, 2, 3), dtype=int32)


In [17]:
print(tensor_three_d.shape)

(4, 2, 3)


In [22]:
tensor_four_d = tf.constant([
[
 [[1,2,0],
 [3,5,-1]],

[[4,5,6],
 [7,-8,9]],

[[10,11,12],
 [13,-14,15]],

 [[16,17,18],
 [13,-14,15]]
],
[
 [[10,20,0],
 [3,5,-1]],

[[40,50,60],
 [7,-8,9]],

[[10,11,12],
 [13,-14,15]],

 [[16,17,18],
 [13,-14,15]]
],

[
 [[100,200,0],
 [3,5,-100]],

[[40,50,60],
 [7,-8,9]],

[[10,11,12],
 [13,-14,15]],

 [[16,17,18],
 [13,-14,15]]
]])

print(tensor_four_d)

tf.Tensor(
[[[[   1    2    0]
   [   3    5   -1]]

  [[   4    5    6]
   [   7   -8    9]]

  [[  10   11   12]
   [  13  -14   15]]

  [[  16   17   18]
   [  13  -14   15]]]


 [[[  10   20    0]
   [   3    5   -1]]

  [[  40   50   60]
   [   7   -8    9]]

  [[  10   11   12]
   [  13  -14   15]]

  [[  16   17   18]
   [  13  -14   15]]]


 [[[ 100  200    0]
   [   3    5 -100]]

  [[  40   50   60]
   [   7   -8    9]]

  [[  10   11   12]
   [  13  -14   15]]

  [[  16   17   18]
   [  13  -14   15]]]], shape=(3, 4, 2, 3), dtype=int32)
