In [73]:
import tensorflow as tf

In [74]:
tensor_index = tf.constant([2,4,9,0,4,1,3])


In [75]:
# get value 4

print(tensor_index[3])



tf.Tensor(0, shape=(), dtype=int32)


In [76]:
print(tensor_index[1],tensor_index[-1])


tf.Tensor(4, shape=(), dtype=int32) tf.Tensor(3, shape=(), dtype=int32)


In [77]:
print(tensor_index[0:4])



tf.Tensor([2 4 9 0], shape=(4,), dtype=int32)


In [78]:
#start:end


#tensor_index[start:end+1]
print(tensor_index)

tf.Tensor([2 4 9 0 4 1 3], shape=(7,), dtype=int32)


In [79]:
tensor_index[0:2+1]


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 9], dtype=int32)>

In [80]:
tensor_index[3:5+1]



<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 4, 1], dtype=int32)>

In [81]:
tensor_index[3:]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 4, 1, 3], dtype=int32)>

In [82]:
tensor_index[3:-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 4, 1], dtype=int32)>

In [83]:
tensor_index[2:-2]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([9, 0, 4], dtype=int32)>

In [84]:
tensor_index[:6]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 4, 9, 0, 4, 1], dtype=int32)>

In [85]:
tensor_index[0:5:2]


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 9, 4], dtype=int32)>

In [86]:
print(tensor_index[0:5:2])

print(" ")

print(tensor_index[0:5:1])

tf.Tensor([2 9 4], shape=(3,), dtype=int32)
 
tf.Tensor([2 4 9 0 4], shape=(5,), dtype=int32)


In [87]:
# 2D tensor

tensor_index_two_d = tf.constant([[1,2,3,4],[6,7,8,9],[10,11,12,14]])

print(tensor_index_two_d)

tf.Tensor(
[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 14]], shape=(3, 4), dtype=int32)


In [88]:
print(tensor_index_two_d[1])


tf.Tensor([6 7 8 9], shape=(4,), dtype=int32)


In [89]:
print(tensor_index_two_d[1,2])



tf.Tensor(8, shape=(), dtype=int32)


In [90]:
print(tensor_index_two_d[1,2:4])



tf.Tensor([8 9], shape=(2,), dtype=int32)


In [91]:
print(tensor_index_two_d[1,1:4+1])


tf.Tensor([7 8 9], shape=(3,), dtype=int32)


In [92]:
print(tensor_index_two_d[0:2,0:3])


tf.Tensor(
[[1 2 3]
 [6 7 8]], shape=(2, 3), dtype=int32)


In [93]:
print(tensor_index_two_d[:,0:3])


tf.Tensor(
[[ 1  2  3]
 [ 6  7  8]
 [10 11 12]], shape=(3, 3), dtype=int32)


In [94]:
print(tensor_index_two_d[:1,0:3])


tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [98]:
print(tensor_index_two_d[0,...])# 1D tensor

print(" ")

print(tensor_index_two_d[0:1,...]) # 2D tensor with column and row

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
 
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)


In [100]:
print(tensor_index_two_d)

print(" ")

print(print(tensor_index_two_d[0:2,1:3]))



tf.Tensor(
[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 14]], shape=(3, 4), dtype=int32)
 
tf.Tensor(
[[2 3]
 [7 8]], shape=(2, 2), dtype=int32)
None


In [102]:
tensor_index_three_d = tf.constant(
    [
      [[1,2,0],
      [3,5,-1]],

      [[4,7,8],
       [9,10,12]],

      [[5,8,8],
       [2,7,0]],

      [[2,1,9],
       [4,3,-2]]
        ]
)
print(tensor_index_three_d)


tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[ 4  7  8]
  [ 9 10 12]]

 [[ 5  8  8]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4  3 -2]]], shape=(4, 2, 3), dtype=int32)


In [103]:
tensor_index_three_d.shape

TensorShape([4, 2, 3])

In [107]:
print(tensor_index_three_d[3,0,2])

# 3rd block, 0th row, 2nd column

# print 9


tf.Tensor(9, shape=(), dtype=int32)


In [108]:
print(tensor_index_three_d[3,0,:])

tf.Tensor([2 1 9], shape=(3,), dtype=int32)


In [111]:
print(tensor_index_three_d[1,1,2])

#print 12


tf.Tensor(12, shape=(), dtype=int32)


In [113]:
print(tensor_index_three_d[2,:,0:2])

tf.Tensor(
[[5 8]
 [2 7]], shape=(2, 2), dtype=int32)
