In [2]:
import tensorflow as tf

In [3]:
#tf. math. abs

# Computes the absolute value of a tensor
# if input is <0 it converts to positive value

In [4]:
x = tf.constant(-0.2)
tensor_absolute = tf.math.abs(
    x,
    name=None
)
print(tensor_absolute)

tf.Tensor(0.2, shape=(), dtype=float32)


In [5]:
x = tf.constant([2,-1,-0.2,3])
tensor_absolute = tf.math.abs(
    x,
    name=None
)
print(tensor_absolute)

tf.Tensor([2.  1.  0.2 3. ], shape=(4,), dtype=float32)


In [6]:
# complex number
# absolute value of complex number
# a+bj is sqrt(a^2+b^2)

x = tf.constant([[-5.5+8j],[-9.9+13j]])
tensor_absolute = tf.math.abs(
    x,
    name=None
)
print(tensor_absolute)

tf.Tensor(
[[ 9.70824392]
 [16.34044063]], shape=(2, 1), dtype=float64)


In [7]:
# tf. math. add

# Returns x +y element - wise



In [8]:
x = tf.constant([2,5,8])
y = tf.constant([1,6,9])

tensor_add=tf.add(x,y)
print(tensor_add)



tf.Tensor([ 3 11 17], shape=(3,), dtype=int32)


In [9]:
x = tf.constant([[2,5,8],[4,10,16]])
y = tf.constant([[1,6,9],[2,12,18]])

tensor_add=tf.add(x,y)
print(tensor_add)


tf.Tensor(
[[ 3 11 17]
 [ 6 22 34]], shape=(2, 3), dtype=int32)


In [10]:
x = tf.constant([[2,5,8],[4,10,16]])
y = tf.constant(1)

tensor_add=tf.add(x,y)
print(tensor_add)

tf.Tensor(
[[ 3  6  9]
 [ 5 11 17]], shape=(2, 3), dtype=int32)


In [11]:
# tf. math. divide_no_nan

# Computes a safe divide which return 0 if y(denominator) is zero



In [12]:
x = tf.constant([2,5,8])
y = tf.constant(0)


tensor_divide = tf.math.divide_no_nan(
    x,
    y,
    name=None
)
print(tensor_divide)


tf.Tensor([0. 0. 0.], shape=(3,), dtype=float64)


In [13]:
x = tf.constant([2,5,8])
y = tf.constant([1,2,10])


tensor_divide = tf.math.divide_no_nan(
    x,
    y,
    name=None
)
print(tensor_divide)

tf.Tensor([2.  2.5 0.8], shape=(3,), dtype=float64)


In [14]:
# tf. math.mutiply
# element wise operation

x = tf.constant([2,3,4,5])

y = tf.constant([[1],[3]])
print(tf.math.multiply(x,y))


tf.Tensor(
[[ 2  3  4  5]
 [ 6  9 12 15]], shape=(2, 4), dtype=int32)


In [15]:
# tf. math. maximum

# Return the max of x and y(i.e x> y ? x:y) element wise



In [16]:

x = tf.constant([2,3,4,5])

y = tf.constant([5,6,1,2])

tensor_max = tf.math.maximum(
    x,y
)
print(tensor_max)

tf.Tensor([5 6 4 5], shape=(4,), dtype=int32)


In [17]:

x = tf.constant([1,0.2,0.3,0.4])

y = tf.constant([-5.])

tensor_max = tf.math.maximum(
    x,y
)
print(tensor_max)

tf.Tensor([1.  0.2 0.3 0.4], shape=(4,), dtype=float32)


In [18]:
# tf. math. minimum

# Return the max of x and y(i.e x< y ? x:y) element wise



In [19]:

x = tf.constant([1,0.2,0.3,0.4])

y = tf.constant([-5.])

tensor_max = tf.math.minimum(
    x,y
)
print(tensor_max)

tf.Tensor([-5. -5. -5. -5.], shape=(4,), dtype=float32)


In [20]:
# tf. math. argmax

# Returns the index with the largest value across axes of a tensor



In [21]:
x = tf.constant([2,20,30,3,6])

tensor_argmax = tf.math.argmax(
    input=x,
    axis=None,
    output_type=tf.dtypes.int64,
    name=None
)
print(tensor_argmax)


# 30 is the highest number. output will have index.



tf.Tensor(2, shape=(), dtype=int64)


In [22]:
x = tf.constant([[5,20,30,3,6],
                [3,7,8,10,12],
                 [15,0,-1,3,4],
                [17,19,1,2,3]]
              )
print(x)

print(" ")

tensor_argmax = tf.math.argmax(
    input=x,
    axis=0,
    output_type=tf.dtypes.int64,
    name=None
)

print(tensor_argmax)
# will print index of max number from each column


tf.Tensor(
[[ 5 20 30  3  6]
 [ 3  7  8 10 12]
 [15  0 -1  3  4]
 [17 19  1  2  3]], shape=(4, 5), dtype=int32)
 
tf.Tensor([3 0 0 1 1], shape=(5,), dtype=int64)


In [23]:
print(x)

print(" ")
tensor_argmax = tf.math.argmax(
    input=x,
    axis=1,
    output_type=tf.dtypes.int64,
    name=None
)

print(tensor_argmax)
# will print index of max number from each row.


tf.Tensor(
[[ 5 20 30  3  6]
 [ 3  7  8 10 12]
 [15  0 -1  3  4]
 [17 19  1  2  3]], shape=(4, 5), dtype=int32)
 
tf.Tensor([2 4 0 1], shape=(4,), dtype=int64)


In [24]:
# tf. math. argin

# Returns the index with the smallest value across axes of a tensor



In [25]:
x = tf.constant([5,20,30,3,6])

tensor_argmin = tf.math.argmin(
    input=x,
    axis=None,
    output_type=tf.dtypes.int64,
    name=None
)

print(tensor_argmax)


tf.Tensor([2 4 0 1], shape=(4,), dtype=int64)


In [26]:
x = tf.constant([[5,20,30,3,6],
                [3,7,8,10,12],
                 [15,0,-1,3,4],
                [17,19,1,2,3]]
              )
print(x)

print(" ")

tensor_argmin = tf.math.argmin(
    input=x,
    axis=1,
    output_type=tf.dtypes.int64,
    name=None
)
print(tensor_argmax)
# will print index of max number from each column


tf.Tensor(
[[ 5 20 30  3  6]
 [ 3  7  8 10 12]
 [15  0 -1  3  4]
 [17 19  1  2  3]], shape=(4, 5), dtype=int32)
 
tf.Tensor([2 4 0 1], shape=(4,), dtype=int64)


In [27]:
x = tf.constant([[5,20,30,3,6],
                [3,7,8,10,12],
                 [15,0,-1,3,4],
                [17,19,1,2,3]]
              )
print(x)

print(" ")

tensor_argmin = tf.math.argmin(
    input=x,
    axis=0,
    output_type=tf.dtypes.int64,
    name=None
)
print(tensor_argmax)
# will print index of max number from each column


tf.Tensor(
[[ 5 20 30  3  6]
 [ 3  7  8 10 12]
 [15  0 -1  3  4]
 [17 19  1  2  3]], shape=(4, 5), dtype=int32)
 
tf.Tensor([2 4 0 1], shape=(4,), dtype=int64)


In [28]:
# tf. math. equal

# Returns the truth value of x==y element wise.



In [29]:
x = tf.constant([2,4])
y = tf.constant([2])

tensor_equal = tf.math.equal(
    x,y,

)

In [30]:
# tf. math. pow

# Computes the power of one value to another
# element wise operation

In [31]:
x = tf.constant([[2,2],[3,3]])
y = tf.constant([[0,6],[2,3]])

tensor_power = tf.math.pow(
    x,y
)
print(tensor_power)


tf.Tensor(
[[ 1 64]
 [ 9 27]], shape=(2, 2), dtype=int32)


In [32]:
# tf. math. reduce_max

# Computes tf.math.maximum of element across dimensions of a tensor


In [33]:
x = tf.constant([1,2,3,4])


tensor_reduce = tf.math.reduce_max(
    input_tensor=x,
    axis=None,
    keepdims= False,
    name=None
)

print(tensor_reduce)


tf.Tensor(4, shape=(), dtype=int32)


In [34]:
x = tf.constant([[1,5,3,4],[6,3,9,0]])


tensor_reduce = tf.math.reduce_max(
    input_tensor=x,
    axis=None,
    keepdims= False,
    name=None
)

print(tensor_reduce)


tf.Tensor(9, shape=(), dtype=int32)


In [37]:
x = tf.constant([[1,5,3,4],[6,3,9,0]])


tensor_reduce = tf.math.reduce_max(
    input_tensor=x,
    axis=None,
    keepdims= True, # will print 2D array. it maintains dimension
    name=None
)

print(tensor_reduce)


tf.Tensor([[9]], shape=(1, 1), dtype=int32)


In [38]:
# tf. math.reduce_sum will return sum of all elements

x = tf.constant([[1,5,3,4],[6,3,9,0]])


tensor_reduce = tf.math.reduce_sum(
    input_tensor=x,
    axis=None,
    keepdims= True, # will print 2D array. it maintains dimension
    name=None
)

print(tensor_reduce)

tf.Tensor([[31]], shape=(1, 1), dtype=int32)


In [40]:
# tf. math.reduce_sum will return sum of all elements

x = tf.constant([[1,5,3,4],[6,3,9,0]])


tensor_reduce = tf.math.reduce_sum(
    input_tensor=x,
    axis=0, # axis = 0 will print array wil element wise addition
    keepdims= False, # will
    name=None
)

print(tensor_reduce)

tf.Tensor([ 7  8 12  4], shape=(4,), dtype=int32)


In [43]:
# tf. math.reduce_sum will return sum of all elements

x = tf.constant([[1,5,3,4],[6,3,9,0]])
print(x)

print(" ")

tensor_reduce = tf.math.reduce_sum(
    input_tensor=x,
    axis=1, #
    keepdims= True, # axis=1 and true means rowwise addition
    name=None
)

print(tensor_reduce)

tf.Tensor(
[[1 5 3 4]
 [6 3 9 0]], shape=(2, 4), dtype=int32)
 
tf.Tensor(
[[13]
 [18]], shape=(2, 1), dtype=int32)


In [36]:
# tf. math. top_k

# Finds values and indices of the k largest entries for the last
# dimension


In [45]:
x =  tf.constant([10,20,30,1,4,5,7,8])

tensor_top_k = tf.math.top_k(x,k=2)

print(tensor_top_k)

# based on value of k it will print k maximum number from tensor



TopKV2(values=<tf.Tensor: shape=(2,), dtype=int32, numpy=array([30, 20], dtype=int32)>, indices=<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 1], dtype=int32)>)


In [46]:
x =  tf.constant([10,20,30,1,4,5,7,8])

tensor_top_k = tf.math.top_k(x,k=4) # 4 maximum value from tensor

print(tensor_top_k)

TopKV2(values=<tf.Tensor: shape=(4,), dtype=int32, numpy=array([30, 20, 10,  8], dtype=int32)>, indices=<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 1, 0, 7], dtype=int32)>)


In [48]:
# tf. math. sigmoid

# Computes sigmoid of x element wise.

# sigmoid(x)= y = 1/(1+exp(-x))



In [50]:
x =  tf.constant([0,1.0,50.0,8.0])
# enter float value only othwise for integer it shows error
tensor_sigmoid = tf.math.sigmoid(
    x,
    name=None
)
print(tensor_sigmoid)


tf.Tensor([0.5        0.7310586  1.         0.99966466], shape=(4,), dtype=float32)
